Ac = 1;
Am = 1;
fc = 1000;
fm = 100;
t = 0:1e-5:0.01;
message_signal = Am * cos(2 * pi * fm * t);
carrier_signal = Ac * cos(2 * pi * fc * t);
modulated_signal = (Ac + message_signal) .* carrier_signal;
figure;
subplot(3,1,1);
plot(t, message_signal);
title('Message Signal');
xlabel('Time (s)');
ylabel('Amplitude');
subplot(3,1,2);
plot(t, carrier_signal);
title('Carrier Signal');
xlabel('Time (s)');
ylabel('Amplitude');
subplot(3,1,3);
plot(t, modulated_signal);
title('DSB-FC Modulated Signal');
xlabel('Time (s)');
ylabel('Amplitude');
